/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* NOTE: If this file is auto-generated, update the generation script to use environment variables */

// Extract projectId from NEXT_PUBLIC_SUPABASE_URL if available
// Format: https://<projectId>.supabase.co
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const projectIdMatch = supabaseUrl.match(/https:\/\/([^.]+)\.supabase\.co/);
export const projectId = projectIdMatch
    ? projectIdMatch[1]
    : process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ID || "";

// Use environment variable for anon key, fallback to empty string
export const publicAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";
